const {test}=require('node:test'),assert=require('node:assert/strict'),{chromium}=require('playwright');const en=require('../apps/mobile/src/live/locales/en.json'),ta=require('../apps/mobile/src/live/locales/ta.json');
test('two workspaces: direct navigation, one account, persisted choice and independent map state', {timeout:180000},async()=>{
const b=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
const p=await b.newPage({viewport:{width:390,height:844}}),errors=[],privateWrites=[];p.on('pageerror',()=>errors.push('page error'));p.on('request',r=>{if(new URL(r.url()).hostname.endsWith('supabase.co'))privateWrites.push(r.method());});await p.goto('http://localhost:8093');
const button=(label)=>p.getByRole('button',{name:label,exact:true});await button(en.find).click();let jobs=p.getByTestId('map-discovery-surface');await jobs.waitFor();await jobs.getByRole('button',{name:en.filters,exact:true}).click();await p.getByLabel(en.customDistance,{exact:true}).fill('17');await button(en.continue).click();await jobs.getByRole('button',{name:en.business,exact:true}).click();await jobs.getByRole('button',{name:en.list,exact:true}).click();
await button(en.profile).last().click();await p.getByText(en.myProfile,{exact:true}).waitFor();await button(en.editProfile).click();await p.getByLabel(en.name,{exact:true}).fill('Kavitha Review');await button(en.save).click();await p.getByText('Kavitha Review',{exact:true}).waitFor();await button(en.settings).click();await button(en.back).first().click();await button(en.post).click();const workers=p.getByTestId('worker-discovery');await workers.waitFor();await workers.locator('[data-map-ready="true"]').waitFor({timeout:60000});assert.equal(await workers.locator('[data-urgency]').count(),0);assert.equal(await workers.locator('[data-worker="true"]').count(),2);await workers.getByRole('button',{name:en.list,exact:true}).click();await workers.getByText('Ramesh',{exact:true}).waitFor();
await button(en.myPosts).last().click();await p.getByText(en.myPosts,{exact:true}).first().waitFor();await button(en.applicants).last().click();await p.getByText(en.applicants,{exact:true}).first().waitFor();await button(en.notifications).last().click();await button(en.profile).last().click();await p.getByText('Kavitha Review',{exact:true}).waitFor();await button(en.profileCredits).click();await p.getByText('12 '+en.availableCredits,{exact:true}).waitFor();await button(en.profile).last().click();await button(en.find).click();await jobs.getByText(en.bakeryHelper,{exact:true}).waitFor();assert.equal(await jobs.getByText(en.electrician,{exact:true}).count(),0);await jobs.getByRole('button',{name:en.filters,exact:true}).click();assert.equal(await p.getByLabel(en.customDistance,{exact:true}).inputValue(),'17');await button(en.continue).click();
for(const [lang,d]of [['English',en],['தமிழ்',ta]]){await button(en.profile).last().click(); await button(en.settings).click(); await button(lang).first().click(); await button(d.profile).last().click(); await button(d.find).click();for(const width of [360,390,412]){await p.setViewportSize({width,height:844});await button(d.profile).last().click();await p.getByText(d.myProfile,{exact:true}).waitFor();await button(d.post).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await button(d.myPosts).last().click();await button(d.applicants).last().click();await button(d.notifications).last().click();await button(d.profile).last().click();await button(d.find).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}}
await button(ta.profile).last().click();await button(ta.post).click();await p.reload();await workers.waitFor();assert.equal(await p.getByText(en.workspaceQuestion,{exact:true}).count(),0);assert.deepEqual(errors,[]);assert.deepEqual(privateWrites,[]);
}finally{await b.close();}});
